/* eslint-disable */
// Auto-generated by scripts/parse-2026-admission-plans.mjs
export const publicHighSchoolPlans2026 = [
  {
    "serial": 1,
    "name": "深圳中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 2060,
    "boardingPlan": 1750,
    "dayPlan": 310,
    "rawText": "面向全市招收ACD类考生1980人，其中D类生182人（住宿生 155人，走读生27人）。另港澳子弟班面向全市招收40名参 1 深圳中学 省一级 公办 2060 1750 310 加深圳中考且中考资格审核通过的持有港澳台居民居住证 2026年招收高一新生安排在泥岗校区教学 或港澳台往来内地/大陆通行证的应届初中毕业生；数理实 验班面向全省招收40名市外省内户籍应届初中毕业生。"
  },
  {
    "serial": 2,
    "name": "深圳中学科技高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 1000,
    "boardingPlan": 1000,
    "dayPlan": 0,
    "rawText": "公办 1000 1000 — 面向全市招收ACD类考生，其中D类生295人 2 深圳中学科技高中 公办 100 100 — 面向深汕合作区招收应届初中毕业生"
  },
  {
    "serial": 3,
    "name": "深圳中学数理高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 1000,
    "boardingPlan": 1000,
    "dayPlan": 0,
    "rawText": "公办 1000 1000 — 面向全市招收ACD类考生，其中D类生295人 3 深圳中学数理高中 公办 100 100 — 面向深汕合作区招收应届初中毕业生"
  },
  {
    "serial": 4,
    "name": "深圳中学实验高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 1000,
    "boardingPlan": 1000,
    "dayPlan": 0,
    "rawText": "公办 1000 1000 — 面向全市招收ACD类考生，其中D类生295人 4 深圳中学实验高中 公办 100 100 — 面向深汕合作区招收应届初中毕业生"
  },
  {
    "serial": 5,
    "name": "深圳实验学校（高中部）",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 565,
    "boardingPlan": 528,
    "dayPlan": 37,
    "rawText": "面向全市招收ACD类考生， 5 深圳实验学校（高中部） 公办 565 528 37 其中D类生55人（住宿生51人，走读生4人） 省一级"
  },
  {
    "serial": 6,
    "name": "深圳实验学校（光明高中部）",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1070,
    "boardingPlan": 1000,
    "dayPlan": 70,
    "rawText": "省一级 面向全市招收ACD类考生， 6 深圳实验学校（光明高中部） 公办 1070 1000 70 其中D类生128人（住宿生120人，走读生8人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 7,
    "name": "深圳实验学校明理高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 1100,
    "boardingPlan": 1000,
    "dayPlan": 100,
    "rawText": "其中D类生128人（住宿生120人，走读生8人） 面向全市招收ACD类考生， 7 深圳实验学校明理高中 公办 1100 1000 100 其中D类生254人（住宿生231人，走读生23人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 8,
    "name": "深圳实验学校崇文高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 990,
    "boardingPlan": 900,
    "dayPlan": 90,
    "rawText": "其中D类生254人（住宿生231人，走读生23人） 面向全市招收ACD类考生， 8 深圳实验学校崇文高中 公办 990 900 90 其中D类生275人（住宿生250人，走读生25人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 9,
    "name": "深圳实验学校卓越高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 880,
    "boardingPlan": 800,
    "dayPlan": 80,
    "rawText": "其中D类生275人（住宿生250人，走读生25人） 面向全市招收ACD类考生， 9 深圳实验学校卓越高中 公办 880 800 80 其中D类生238人（住宿生216人，走读生22人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 10,
    "name": "深圳实验学校至臻高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 440,
    "boardingPlan": 400,
    "dayPlan": 40,
    "rawText": "其中D类生238人（住宿生216人，走读生22人） 面向全市招收ACD类考生， 10 深圳实验学校至臻高中 公办 440 400 40 其中D类生106人（住宿生96人，走读生10人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 11,
    "name": "深圳外国语学校",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 847,
    "boardingPlan": 782,
    "dayPlan": 65,
    "rawText": "其中D类生106人（住宿生96人，走读生10人） 面向全市招收ACD类考生， 11 深圳外国语学校 公办 847 782 65 其中D类生97人（住宿生90人，走读生7人） 省一级"
  },
  {
    "serial": 12,
    "name": "深圳外国语学校龙华高中部",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 963,
    "boardingPlan": 900,
    "dayPlan": 63,
    "rawText": "省一级 面向全市招收ACD类考生， 12 深圳外国语学校龙华高中部 公办 963 900 63 其中D类生179人（住宿生167人，走读生12人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 13,
    "name": "深圳外国语学校致远高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "其中D类生179人（住宿生167人，走读生12人） 面向全市招收ACD类考生， 13 深圳外国语学校致远高中 公办 660 600 60 其中D类生186人（住宿生169人，走读生17人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 14,
    "name": "深圳外国语学校弘知高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 1100,
    "boardingPlan": 1000,
    "dayPlan": 100,
    "rawText": "其中D类生186人（住宿生169人，走读生17人） 面向全市招收ACD类考生， 14 深圳外国语学校弘知高中 公办 1100 1000 100 其中D类生306人（住宿生278人，走读生28人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 15,
    "name": "深圳外国语学校博雅高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 990,
    "boardingPlan": 900,
    "dayPlan": 90,
    "rawText": "其中D类生306人（住宿生278人，走读生28人） 面向全市招收ACD类考生， 15 深圳外国语学校博雅高中 公办 990 900 90 其中D类生275人（住宿生250人，走读生25人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 16,
    "name": "深圳外国语学校理工高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 550,
    "boardingPlan": 500,
    "dayPlan": 50,
    "rawText": "其中D类生275人（住宿生250人，走读生25人） 面向全市招收ACD类考生， 16 深圳外国语学校理工高中 公办 550 500 50 其中D类生139人（住宿生126人，走读生13人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 17,
    "name": "深圳市高级中学中心校区",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 963,
    "boardingPlan": 900,
    "dayPlan": 63,
    "rawText": "其中D类生139人（住宿生126人，走读生13人） 面向全市招收ACD类考生， 17 深圳市高级中学中心校区 公办 963 900 63 其中D类生178人（住宿生166人，走读生12人） 省一级"
  },
  {
    "serial": 18,
    "name": "深圳市高级中学东校区",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1070,
    "boardingPlan": 1000,
    "dayPlan": 70,
    "rawText": "省一级 面向全市招收ACD类考生， 18 深圳市高级中学东校区 公办 1070 1000 70 其中D类生247人（住宿生231人，走读生16人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 19,
    "name": "深圳市高级中学创新高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 880,
    "boardingPlan": 800,
    "dayPlan": 80,
    "rawText": "其中D类生247人（住宿生231人，走读生16人） 面向全市招收ACD类考生， 19 深圳市高级中学创新高中 公办 880 800 80 其中D类生202人（住宿生184人，走读生18人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 20,
    "name": "深圳市高级中学文博高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 1100,
    "boardingPlan": 1000,
    "dayPlan": 100,
    "rawText": "其中D类生202人（住宿生184人，走读生18人） 面向全市招收ACD类考生， 20 深圳市高级中学文博高中 公办 1100 1000 100 其中D类生265人（住宿生241人，走读生24人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 21,
    "name": "深圳市高级中学理慧高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 990,
    "boardingPlan": 900,
    "dayPlan": 90,
    "rawText": "其中D类生265人（住宿生241人，走读生24人） 面向全市招收ACD类考生， 21 深圳市高级中学理慧高中 公办 990 900 90 其中D类生229人（住宿生208人，走读生21人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 22,
    "name": "深圳市高级中学有为高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 550,
    "boardingPlan": 500,
    "dayPlan": 50,
    "rawText": "其中D类生229人（住宿生208人，走读生21人） 面向全市招收ACD类考生， 22 深圳市高级中学有为高中 公办 550 500 50 其中D类生130人（住宿生118人，走读生12人） 深圳市第三高级中学（国内高考 面向全市招收ACD类考生，"
  },
  {
    "serial": 23,
    "name": "深圳市第三高级中学（国家留学基金委自费出国留学班）",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 376,
    "boardingPlan": 376,
    "dayPlan": 0,
    "rawText": "manual-fix-23-overseas"
  },
  {
    "serial": 23,
    "name": "深圳市第三高级中学（国内高考班）",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 695,
    "boardingPlan": 650,
    "dayPlan": 45,
    "rawText": "manual-fix-23-domestic"
  },
  {
    "serial": 24,
    "name": "深圳启元中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "2026-2027学年在民办学校借址办学，后续搬回到学 面向全市招收ACD类考生， 24 深圳启元中学 公办 660 600 60 校永久校区（永久校区地址：龙岗区龙城街道回龙 其中D类生112人（住宿生102人，走读生10人） 埔社区盐龙大道辅道）"
  },
  {
    "serial": 25,
    "name": "深圳益新中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 770,
    "boardingPlan": 600,
    "dayPlan": 170,
    "rawText": "面向全市招收ACD类考生， 25 深圳益新中学 公办 770 600 170 地址：龙华区福城街道福花路南侧 其中D类生123人（住宿生96人，走读生27人） 深圳大学附属中学中心校区（深大 面向全市招收ACD类考生，"
  },
  {
    "serial": 26,
    "name": "深圳大学附属中学（深大附中）",
    "level": "",
    "nature": "公办",
    "totalPlan": 642,
    "boardingPlan": 600,
    "dayPlan": 42,
    "rawText": "manual-fix-26"
  },
  {
    "serial": 27,
    "name": "深圳大学附属中学盐田校区（深大附中盐田校区）",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 330,
    "boardingPlan": 300,
    "dayPlan": 30,
    "rawText": "manual-fix-27"
  },
  {
    "serial": 28,
    "name": "深圳大学附属实验中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "面向全市招收ACD类考生， 28 深圳大学附属实验中学 公办 660 600 60 其中D类生156人（住宿生142人，走读生14人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 29,
    "name": "深圳市第二实验学校",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 481,
    "boardingPlan": 450,
    "dayPlan": 31,
    "rawText": "其中D类生156人（住宿生142人，走读生14人） 面向全市招收ACD类考生， 29 深圳市第二实验学校 省一级 公办 481 450 31 其中D类生101人（住宿生94人，走读生7人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 30,
    "name": "深圳市第二实验学校明远高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "其中D类生101人（住宿生94人，走读生7人） 面向全市招收ACD类考生， 30 深圳市第二实验学校明远高中 公办 660 600 60 其中D类生149人（住宿生135人，走读生14人）"
  },
  {
    "serial": 31,
    "name": "深圳市第二高级中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1070,
    "boardingPlan": 1000,
    "dayPlan": 70,
    "rawText": "住宿生 走读生 面向全市招收ACD类考生， 31 深圳市第二高级中学 公办 1070 1000 70 其中D类生229人（住宿生214人，走读生15人） 省一级"
  },
  {
    "serial": 32,
    "name": "深圳市第二高级中学宝安高中部",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 880,
    "boardingPlan": 800,
    "dayPlan": 80,
    "rawText": "省一级 面向全市招收ACD类考生， 32 深圳市第二高级中学宝安高中部 公办 880 800 80 地址：宝安区新桥街道中心路12-14号 其中D类生134人（住宿生122人，走读生12人）"
  },
  {
    "serial": 33,
    "name": "深圳市第二高级中学深汕实验学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 900,
    "boardingPlan": 900,
    "dayPlan": 0,
    "rawText": "公办 900 900 — 面向全市招收ACD类考生，其中D类生274人 33 深圳市第二高级中学深汕实验学校 公办 100 100 — 面向深汕合作区招收应届初中毕业生"
  },
  {
    "serial": 34,
    "name": "深圳第二外国语学校",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 963,
    "boardingPlan": 900,
    "dayPlan": 63,
    "rawText": "面向全市招收ACD类考生， 34 深圳第二外国语学校 省一级 公办 963 900 63 其中D类生268人（住宿生250人，走读生18人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 35,
    "name": "深圳科学高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 1177,
    "boardingPlan": 1100,
    "dayPlan": 77,
    "rawText": "其中D类生268人（住宿生250人，走读生18人） 面向全市招收ACD类考生， 35 深圳科学高中 公办 1177 1100 77 其中D类生260人（住宿生243人，走读生17人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 36,
    "name": "深圳科学高中龙岗分校",
    "level": "",
    "nature": "公办",
    "totalPlan": 605,
    "boardingPlan": 550,
    "dayPlan": 55,
    "rawText": "其中D类生260人（住宿生243人，走读生17人） 面向全市招收ACD类考生， 36 深圳科学高中龙岗分校 公办 605 550 55 其中D类生149人（住宿生135人，走读生14人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 37,
    "name": "深圳市第七高级中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 1070,
    "boardingPlan": 1000,
    "dayPlan": 70,
    "rawText": "其中D类生149人（住宿生135人，走读生14人） 面向全市招收ACD类考生， 37 深圳市第七高级中学 公办 1070 1000 70 其中D类生298人（住宿生279人，走读生19人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 38,
    "name": "南方科技大学附属中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 880,
    "boardingPlan": 800,
    "dayPlan": 80,
    "rawText": "其中D类生298人（住宿生279人，走读生19人） 面向全市招收ACD类考生， 38 南方科技大学附属中学 公办 880 800 80 其中D类生198人（住宿生180人，走读生18人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 39,
    "name": "广东实验中学深圳学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 770,
    "boardingPlan": 700,
    "dayPlan": 70,
    "rawText": "其中D类生198人（住宿生180人，走读生18人） 面向全市招收ACD类考生， 39 广东实验中学深圳学校 公办 770 700 70 其中D类生182人（住宿生165人，走读生17人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 40,
    "name": "深圳技术大学附属中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "其中D类生182人（住宿生165人，走读生17人） 面向全市招收ACD类考生， 40 深圳技术大学附属中学 公办 660 600 60 其中D类生181人（住宿生165人，走读生16人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 41,
    "name": "东北师范大学附属中学深圳学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "其中D类生181人（住宿生165人，走读生16人） 面向全市招收ACD类考生， 41 东北师范大学附属中学深圳学校 公办 660 600 60 其中D类生181人（住宿生165人，走读生16人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 42,
    "name": "深圳北理莫斯科大学附属实验中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "其中D类生181人（住宿生165人，走读生16人） 面向全市招收ACD类考生， 42 深圳北理莫斯科大学附属实验中学 公办 660 600 60 其中D类生138人（住宿生125人，走读生13人）"
  },
  {
    "serial": 43,
    "name": "深圳理工大学附属中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 440,
    "boardingPlan": 400,
    "dayPlan": 40,
    "rawText": "2026-2027学年在“深圳理工大学”借址办学（地 面向全市招收ACD类考生， 43 深圳理工大学附属中学 公办 440 400 40 址：光明区公常路1号），后续搬回到学校永久校区 其中D类生69人（住宿生63人，走读生6人） （地址：宝安区航城街道黄田社区宝安教育城）"
  },
  {
    "serial": 44,
    "name": "深圳市曙光中学（综合高中）",
    "level": "",
    "nature": "公办",
    "totalPlan": 770,
    "boardingPlan": 600,
    "dayPlan": 170,
    "rawText": "2026-2027学年在“深圳益新中学”借址办学（地 面向全市招收ACD类考生， 址：龙华区福城街道福花路南侧），后续搬回到学 44 深圳市曙光中学（综合高中） 公办 770 600 170 其中D类生119人（住宿生93人，走读生26人） 校永久校区（地址：坪山区龙田街道规划绿梓大道 与规划龙宝路交汇处）"
  },
  {
    "serial": 45,
    "name": "深圳创新高级中学（综合高中）",
    "level": "",
    "nature": "公办",
    "totalPlan": 700,
    "boardingPlan": 700,
    "dayPlan": 0,
    "rawText": "2026-2027学年在“深圳益新中学”借址办学（地 址：龙华区福城街道福花路南侧），后续搬回到学 45 深圳创新高级中学（综合高中） 公办 700 700 — 面向全市招收ACD类考生，其中D类生112人 校永久校区（地址：深汕特别合作区科教大道1688 号）"
  },
  {
    "serial": 46,
    "name": "深圳市第一职业技术学校（综合高中班）",
    "level": "",
    "nature": "公办",
    "totalPlan": 120,
    "boardingPlan": 120,
    "dayPlan": 0,
    "rawText": "manual-fix-46"
  },
  {
    "serial": 47,
    "name": "深圳市体育实验学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 50,
    "boardingPlan": 50,
    "dayPlan": 0,
    "rawText": "中班） 47 深圳市体育实验学校 公办 50 50 — 面向全市招收ACD类考生 福田区"
  },
  {
    "serial": 48,
    "name": "红岭中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1337,
    "boardingPlan": 1250,
    "dayPlan": 87,
    "rawText": "面向全市招收ACD类考生， 48 红岭中学 省一级 公办 1337 1250 87 其中D类生280人（住宿生262人，走读生18人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 49,
    "name": "福田中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1100,
    "boardingPlan": 1000,
    "dayPlan": 100,
    "rawText": "其中D类生280人（住宿生262人，走读生18人） 面向全市招收ACD类考生， 49 福田中学 省一级 公办 1100 1000 100 其中D类生230人（住宿生209人，走读生21人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 50,
    "name": "北京大学附属中学深圳学校",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 535,
    "boardingPlan": 500,
    "dayPlan": 35,
    "rawText": "其中D类生230人（住宿生209人，走读生21人） 面向全市招收ACD类考生， 50 北京大学附属中学深圳学校 省一级 公办 535 500 35 其中D类生121人（住宿生113人，走读生8人） 西交利物浦大学基础教育集团外国 面向全市招收ACD类考生，"
  },
  {
    "serial": 51,
    "name": "西交利物浦大学基础教育集团外国语高级中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 749,
    "boardingPlan": 700,
    "dayPlan": 49,
    "rawText": "manual-fix-51"
  },
  {
    "serial": 52,
    "name": "香港中文大学(深圳)附属明德高级中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "manual-fix-52"
  },
  {
    "serial": 53,
    "name": "翠园中学（爱国路校区）",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 440,
    "boardingPlan": 400,
    "dayPlan": 40,
    "rawText": "面向全市招收ACD类考生， 53 翠园中学（爱国路校区） 公办 440 400 40 地址：罗湖区爱国路2011号 其中D类生68人（住宿生62人，走读生6人） 省一级"
  },
  {
    "serial": 54,
    "name": "翠园中学（东门北路校区）",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 642,
    "boardingPlan": 500,
    "dayPlan": 142,
    "rawText": "省一级 面向全市招收ACD类考生， 54 翠园中学（东门北路校区） 公办 642 500 142 地址：罗湖区东门北路1016号 其中D类生108人（住宿生84人，走读生24人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 55,
    "name": "罗湖高级中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 532,
    "boardingPlan": 500,
    "dayPlan": 32,
    "rawText": "其中D类生108人（住宿生84人，走读生24人） 面向全市招收ACD类考生， 55 罗湖高级中学 省一级 公办 532 500 32 其中D类生141人（住宿生133人，走读生8人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 56,
    "name": "罗湖外语学校",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 770,
    "boardingPlan": 700,
    "dayPlan": 70,
    "rawText": "其中D类生141人（住宿生133人，走读生8人） 面向全市招收ACD类考生， 56 罗湖外语学校 省一级 公办 770 700 70 其中D类生152人（住宿生138人，走读生14人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 57,
    "name": "深圳市美术学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 440,
    "boardingPlan": 400,
    "dayPlan": 40,
    "rawText": "其中D类生152人（住宿生138人，走读生14人） 面向全市招收ACD类考生， 57 深圳市美术学校 公办 440 400 40 其中D类生128人（住宿生116人，走读生12人） 深圳市行知职业技术学校（综合高"
  },
  {
    "serial": 58,
    "name": "深圳市行知职业技术学校（综合高中班）",
    "level": "",
    "nature": "公办",
    "totalPlan": 165,
    "boardingPlan": 165,
    "dayPlan": 0,
    "rawText": "manual-fix-58"
  },
  {
    "serial": 59,
    "name": "盐田高级中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 1070,
    "boardingPlan": 1000,
    "dayPlan": 70,
    "rawText": "面向全市招收ACD类考生， 59 盐田高级中学 公办 1070 1000 70 其中D类生257人（住宿生240人，走读生17人）"
  },
  {
    "serial": 60,
    "name": "深圳市盐港中学（综合高中班）",
    "level": "",
    "nature": "公办",
    "totalPlan": 107,
    "boardingPlan": 107,
    "dayPlan": 0,
    "rawText": "其中D类生257人（住宿生240人，走读生17人） 60 深圳市盐港中学（综合高中班） 公办 107 107 — 面向全市招收ACD类考生 仅限音乐、体育、美术方向"
  },
  {
    "serial": 61,
    "name": "南头中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 941,
    "boardingPlan": 600,
    "dayPlan": 341,
    "rawText": "面向全市招收ACD类考生， 61 南头中学 省一级 公办 941 600 341 其中D类生222人（住宿生142人，走读生80人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 62,
    "name": "育才中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1100,
    "boardingPlan": 950,
    "dayPlan": 150,
    "rawText": "其中D类生222人（住宿生142人，走读生80人） 面向全市招收ACD类考生， 62 育才中学 公办 1100 950 150 地址：南山区桃源街道峰景社区 其中D类生157人（住宿生136人，走读生21人） 省一级"
  },
  {
    "serial": 63,
    "name": "育才一中",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 642,
    "boardingPlan": 600,
    "dayPlan": 42,
    "rawText": "省一级 面向全市招收ACD类考生， 原“育才中学蛇口校区”更名，地址：南山区招商 63 育才一中 公办 642 600 42 其中D类生108人（住宿生101人，走读生7人） 街道花果山社区 面向全市招收ACD类考生，"
  },
  {
    "serial": 64,
    "name": "华侨城高级中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 856,
    "boardingPlan": 800,
    "dayPlan": 56,
    "rawText": "其中D类生108人（住宿生101人，走读生7人） 街道花果山社区 面向全市招收ACD类考生， 64 华侨城高级中学 省一级 公办 856 800 56 其中D类生174人（住宿生163人，走读生11人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 65,
    "name": "北京师范大学南山附属学校",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 440,
    "boardingPlan": 400,
    "dayPlan": 40,
    "rawText": "其中D类生174人（住宿生163人，走读生11人） 面向全市招收ACD类考生， 65 北京师范大学南山附属学校 省一级 公办 440 400 40 其中D类生79人（住宿生72人，走读生7人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 66,
    "name": "南山外国语学校（集团）高级中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 642,
    "boardingPlan": 600,
    "dayPlan": 42,
    "rawText": "其中D类生79人（住宿生72人，走读生7人） 面向全市招收ACD类考生， 66 南山外国语学校（集团）高级中学 省一级 公办 642 600 42 其中D类生124人（住宿生116人，走读生8人）"
  },
  {
    "serial": 67,
    "name": "宝安中学（集团）高中部",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1070,
    "boardingPlan": 1000,
    "dayPlan": 70,
    "rawText": "面向全市招收ACD类考生， 67 宝安中学（集团）高中部 省一级 公办 1070 1000 70 其中D类生198人（住宿生185人，走读生13人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 68,
    "name": "新安中学（集团）高中部",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 856,
    "boardingPlan": 760,
    "dayPlan": 96,
    "rawText": "其中D类生198人（住宿生185人，走读生13人） 面向全市招收ACD类考生， 68 新安中学（集团）高中部 省一级 公办 856 760 96 其中D类生204人（住宿生181人，走读生23人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 69,
    "name": "宝安第一外国语学校",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 803,
    "boardingPlan": 750,
    "dayPlan": 53,
    "rawText": "其中D类生204人（住宿生181人，走读生23人） 面向全市招收ACD类考生， 69 宝安第一外国语学校 省一级 公办 803 750 53 其中D类生190人（住宿生177人，走读生13人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 70,
    "name": "西乡中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1070,
    "boardingPlan": 1000,
    "dayPlan": 70,
    "rawText": "其中D类生190人（住宿生177人，走读生13人） 面向全市招收ACD类考生， 70 西乡中学 省一级 公办 1070 1000 70 其中D类生278人（住宿生260人，走读生18人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 71,
    "name": "沙井中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 650,
    "boardingPlan": 600,
    "dayPlan": 50,
    "rawText": "其中D类生278人（住宿生260人，走读生18人） 面向全市招收ACD类考生， 71 沙井中学 省一级 公办 650 600 50 其中D类生198人（住宿生183人，走读生15人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 72,
    "name": "松岗中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 321,
    "boardingPlan": 300,
    "dayPlan": 21,
    "rawText": "其中D类生198人（住宿生183人，走读生15人） 面向全市招收ACD类考生， 72 松岗中学 省一级 公办 321 300 21 其中D类生83人（住宿生78人，走读生5人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 73,
    "name": "石岩外国语学校",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 495,
    "boardingPlan": 400,
    "dayPlan": 95,
    "rawText": "其中D类生83人（住宿生78人，走读生5人） 面向全市招收ACD类考生， 73 石岩外国语学校 省一级 公办 495 400 95 其中D类生144人（住宿生116人，走读生28人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 74,
    "name": "深圳市福海中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 707,
    "boardingPlan": 600,
    "dayPlan": 107,
    "rawText": "其中D类生144人（住宿生116人，走读生28人） 面向全市招收ACD类考生， 74 深圳市福海中学 公办 707 600 107 其中D类生164人（住宿生139人，走读生25人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 75,
    "name": "深圳市龙津中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 1155,
    "boardingPlan": 1000,
    "dayPlan": 155,
    "rawText": "其中D类生164人（住宿生139人，走读生25人） 面向全市招收ACD类考生， 75 深圳市龙津中学 公办 1155 1000 155 其中D类生322人（住宿生279人，走读生43人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 76,
    "name": "深圳市燕川中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 1155,
    "boardingPlan": 1000,
    "dayPlan": 155,
    "rawText": "其中D类生322人（住宿生279人，走读生43人） 面向全市招收ACD类考生， 76 深圳市燕川中学 公办 1155 1000 155 其中D类生327人（住宿生283人，走读生44人）"
  },
  {
    "serial": 77,
    "name": "龙城高级中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1070,
    "boardingPlan": 1000,
    "dayPlan": 70,
    "rawText": "面向全市招收ACD类考生， 77 龙城高级中学 省一级 公办 1070 1000 70 其中D类生245人（住宿生229人，走读生16人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 78,
    "name": "平冈中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 750,
    "boardingPlan": 700,
    "dayPlan": 50,
    "rawText": "其中D类生245人（住宿生229人，走读生16人） 面向全市招收ACD类考生， 78 平冈中学 省一级 公办 750 700 50 其中D类生178人（住宿生166人，走读生12人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 79,
    "name": "深圳市龙岗区第二高级中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1070,
    "boardingPlan": 1000,
    "dayPlan": 70,
    "rawText": "其中D类生178人（住宿生166人，走读生12人） 面向全市招收ACD类考生， 79 深圳市龙岗区第二高级中学 省一级 公办 1070 1000 70 原“布吉高级中学”更名 其中D类生325人（住宿生304人，走读生21人）"
  },
  {
    "serial": 80,
    "name": "布吉中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 460,
    "boardingPlan": 0,
    "dayPlan": 460,
    "rawText": "manual-fix-80"
  },
  {
    "serial": 81,
    "name": "横岗高级中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 856,
    "boardingPlan": 800,
    "dayPlan": 56,
    "rawText": "面向全市招收ACD类考生， 81 横岗高级中学 省一级 公办 856 800 56 其中D类生259人（住宿生242人，走读生17人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 82,
    "name": "平湖外国语学校",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 350,
    "boardingPlan": 300,
    "dayPlan": 50,
    "rawText": "其中D类生259人（住宿生242人，走读生17人） 面向全市招收ACD类考生， 82 平湖外国语学校 省一级 公办 350 300 50 其中D类生107人（住宿生92人，走读生15人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 83,
    "name": "华中师范大学龙岗附属中学",
    "level": "市一级",
    "nature": "公办",
    "totalPlan": 1070,
    "boardingPlan": 1000,
    "dayPlan": 70,
    "rawText": "其中D类生107人（住宿生92人，走读生15人） 面向全市招收ACD类考生， 83 华中师范大学龙岗附属中学 市一级 公办 1070 1000 70 其中D类生298人（住宿生279人，走读生19人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 84,
    "name": "龙岗区实验高级中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 440,
    "boardingPlan": 400,
    "dayPlan": 40,
    "rawText": "其中D类生298人（住宿生279人，走读生19人） 面向全市招收ACD类考生， 84 龙岗区实验高级中学 公办 440 400 40 其中D类生116人（住宿生105人，走读生11人）"
  },
  {
    "serial": 85,
    "name": "龙华中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 420,
    "boardingPlan": 300,
    "dayPlan": 120,
    "rawText": "面向全市招收ACD类考生， 85 龙华中学 省一级 公办 420 300 120 其中D类生129人（住宿生92人，走读生37人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 86,
    "name": "观澜中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1100,
    "boardingPlan": 1000,
    "dayPlan": 100,
    "rawText": "其中D类生129人（住宿生92人，走读生37人） 面向全市招收ACD类考生， 86 观澜中学 省一级 公办 1100 1000 100 其中D类生296人（住宿生269人，走读生27人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 87,
    "name": "龙华高级中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 642,
    "boardingPlan": 600,
    "dayPlan": 42,
    "rawText": "其中D类生296人（住宿生269人，走读生27人） 面向全市招收ACD类考生， 87 龙华高级中学 公办 642 600 42 其中D类生144人（住宿生135人，走读生9人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 88,
    "name": "深圳市艺术高中",
    "level": "",
    "nature": "公办",
    "totalPlan": 440,
    "boardingPlan": 400,
    "dayPlan": 40,
    "rawText": "其中D类生144人（住宿生135人，走读生9人） 面向全市招收ACD类考生， 88 深圳市艺术高中 公办 440 400 40 其中D类生129人（住宿生117人，走读生12人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 89,
    "name": "深圳市格致中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "其中D类生129人（住宿生117人，走读生12人） 面向全市招收ACD类考生， 89 深圳市格致中学 公办 660 600 60 其中D类生186人（住宿生169人，走读生17人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 90,
    "name": "深圳市红山中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "其中D类生186人（住宿生169人，走读生17人） 面向全市招收ACD类考生， 90 深圳市红山中学 公办 660 600 60 其中D类生186人（住宿生169人，走读生17人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 91,
    "name": "深圳市龙华外国语高级中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "其中D类生186人（住宿生169人，走读生17人） 面向全市招收ACD类考生， 91 深圳市龙华外国语高级中学 公办 660 600 60 其中D类生186人（住宿生169人，走读生17人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 92,
    "name": "深圳市致理中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 1650,
    "boardingPlan": 1500,
    "dayPlan": 150,
    "rawText": "其中D类生186人（住宿生169人，走读生17人） 面向全市招收ACD类考生， 92 深圳市致理中学 公办 1650 1500 150 其中D类生406人（住宿生369人，走读生37人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 93,
    "name": "深圳市龙华科技实验高级中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 1705,
    "boardingPlan": 1550,
    "dayPlan": 155,
    "rawText": "其中D类生406人（住宿生369人，走读生37人） 面向全市招收ACD类考生， 93 深圳市龙华科技实验高级中学 公办 1705 1550 155 其中D类生331人（住宿生301人，走读生30人）"
  },
  {
    "serial": 94,
    "name": "坪山高级中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 800,
    "boardingPlan": 700,
    "dayPlan": 100,
    "rawText": "面向全市招收ACD类考生， 94 坪山高级中学 省一级 公办 800 700 100 其中D类生212人（住宿生185人，走读生27人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 95,
    "name": "深圳市聚龙科学中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 1100,
    "boardingPlan": 1000,
    "dayPlan": 100,
    "rawText": "其中D类生212人（住宿生185人，走读生27人） 面向全市招收ACD类考生， 95 深圳市聚龙科学中学 公办 1100 1000 100 其中D类生313人（住宿生285人，走读生28人）"
  },
  {
    "serial": 96,
    "name": "光明区高级中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 1541,
    "boardingPlan": 1440,
    "dayPlan": 101,
    "rawText": "面向全市招收ACD类考生， 96 光明区高级中学 省一级 公办 1541 1440 101 其中D类生432人（住宿生404人，走读生28人） 面向全市招收ACD类考生，"
  },
  {
    "serial": 97,
    "name": "光明中学",
    "level": "省一级",
    "nature": "公办",
    "totalPlan": 642,
    "boardingPlan": 600,
    "dayPlan": 42,
    "rawText": "其中D类生432人（住宿生404人，走读生28人） 面向全市招收ACD类考生， 97 光明中学 省一级 公办 642 600 42 其中D类生194人（住宿生181人，走读生13人） 中国科学院深圳理工大学附属实验 面向全市招收ACD类考生，"
  },
  {
    "serial": 98,
    "name": "中国科学院深圳理工大学附属实验高级中学（中科附高）",
    "level": "",
    "nature": "公办",
    "totalPlan": 770,
    "boardingPlan": 700,
    "dayPlan": 70,
    "rawText": "manual-fix-98"
  },
  {
    "serial": 99,
    "name": "人大附中深圳学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 1000,
    "boardingPlan": 1000,
    "dayPlan": 0,
    "rawText": "大鹏新区 99 人大附中深圳学校 公办 1000 1000 — 面向全市招收ACD类考生，其中D类生210人 面向全市招收ACD类考生，"
  },
  {
    "serial": 100,
    "name": "红岭教育集团大鹏华侨中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "boardingPlan": 600,
    "dayPlan": 60,
    "rawText": "面向全市招收ACD类考生， 100 红岭教育集团大鹏华侨中学 公办 660 600 60 其中D类生156人（住宿生142人，走读生14人）"
  }
] as const;

export const quotaPlans2026 = [
  {
    "serial": 1,
    "name": "深圳中学",
    "acQuota": 899,
    "dQuota": 91,
    "acdQuota": 0,
    "rawText": "1 深圳中学 899 91"
  },
  {
    "serial": 2,
    "name": "深圳中学科技高中",
    "acQuota": 353,
    "dQuota": 148,
    "acdQuota": 0,
    "rawText": "2 深圳中学科技高中 353 148"
  },
  {
    "serial": 3,
    "name": "深圳中学数理高中",
    "acQuota": 353,
    "dQuota": 148,
    "acdQuota": 0,
    "rawText": "3 深圳中学数理高中 353 148"
  },
  {
    "serial": 4,
    "name": "深圳中学实验高中",
    "acQuota": 353,
    "dQuota": 148,
    "acdQuota": 0,
    "rawText": "4 深圳中学实验高中 353 148"
  },
  {
    "serial": 5,
    "name": "深圳实验学校（高中部）",
    "acQuota": 255,
    "dQuota": 28,
    "acdQuota": 0,
    "rawText": "5 深圳实验学校（高中部） 255 28"
  },
  {
    "serial": 6,
    "name": "深圳实验学校（光明高中部）",
    "acQuota": 471,
    "dQuota": 64,
    "acdQuota": 0,
    "rawText": "6 深圳实验学校（光明高中部） 471 64"
  },
  {
    "serial": 7,
    "name": "深圳实验学校明理高中",
    "acQuota": 423,
    "dQuota": 127,
    "acdQuota": 0,
    "rawText": "7 深圳实验学校明理高中 423 127"
  },
  {
    "serial": 8,
    "name": "深圳实验学校崇文高中",
    "acQuota": 358,
    "dQuota": 138,
    "acdQuota": 0,
    "rawText": "8 深圳实验学校崇文高中 358 138"
  },
  {
    "serial": 9,
    "name": "深圳实验学校卓越高中",
    "acQuota": 321,
    "dQuota": 119,
    "acdQuota": 0,
    "rawText": "9 深圳实验学校卓越高中 321 119"
  },
  {
    "serial": 10,
    "name": "深圳实验学校至臻高中",
    "acQuota": 167,
    "dQuota": 53,
    "acdQuota": 0,
    "rawText": "10 深圳实验学校至臻高中 167 53"
  },
  {
    "serial": 11,
    "name": "深圳外国语学校",
    "acQuota": 375,
    "dQuota": 49,
    "acdQuota": 0,
    "rawText": "11 深圳外国语学校 375 49"
  },
  {
    "serial": 12,
    "name": "深圳外国语学校龙华高中部",
    "acQuota": 392,
    "dQuota": 90,
    "acdQuota": 0,
    "rawText": "12 深圳外国语学校龙华高中部 392 90"
  },
  {
    "serial": 13,
    "name": "深圳外国语学校致远高中",
    "acQuota": 237,
    "dQuota": 93,
    "acdQuota": 0,
    "rawText": "13 深圳外国语学校致远高中 237 93"
  },
  {
    "serial": 14,
    "name": "深圳外国语学校弘知高中",
    "acQuota": 397,
    "dQuota": 153,
    "acdQuota": 0,
    "rawText": "14 深圳外国语学校弘知高中 397 153"
  },
  {
    "serial": 15,
    "name": "深圳外国语学校博雅高中",
    "acQuota": 358,
    "dQuota": 138,
    "acdQuota": 0,
    "rawText": "15 深圳外国语学校博雅高中 358 138"
  },
  {
    "serial": 16,
    "name": "深圳外国语学校理工高中",
    "acQuota": 206,
    "dQuota": 70,
    "acdQuota": 0,
    "rawText": "16 深圳外国语学校理工高中 206 70"
  },
  {
    "serial": 17,
    "name": "深圳市高级中学中心校区",
    "acQuota": 393,
    "dQuota": 89,
    "acdQuota": 0,
    "rawText": "17 深圳市高级中学中心校区 393 89"
  },
  {
    "serial": 18,
    "name": "深圳市高级中学东校区",
    "acQuota": 412,
    "dQuota": 124,
    "acdQuota": 0,
    "rawText": "18 深圳市高级中学东校区 412 124"
  },
  {
    "serial": 19,
    "name": "深圳市高级中学创新高中",
    "acQuota": 339,
    "dQuota": 101,
    "acdQuota": 0,
    "rawText": "19 深圳市高级中学创新高中 339 101"
  },
  {
    "serial": 20,
    "name": "深圳市高级中学文博高中",
    "acQuota": 418,
    "dQuota": 133,
    "acdQuota": 0,
    "rawText": "20 深圳市高级中学文博高中 418 133"
  },
  {
    "serial": 21,
    "name": "深圳市高级中学理慧高中",
    "acQuota": 381,
    "dQuota": 115,
    "acdQuota": 0,
    "rawText": "21 深圳市高级中学理慧高中 381 115"
  },
  {
    "serial": 22,
    "name": "深圳市高级中学有为高中",
    "acQuota": 210,
    "dQuota": 65,
    "acdQuota": 0,
    "rawText": "22 深圳市高级中学有为高中 210 65"
  },
  {
    "serial": 23,
    "name": "深圳市第三高级中学 （国内高考班）",
    "acQuota": 259,
    "dQuota": 89,
    "acdQuota": 0,
    "rawText": "23 深圳市第三高级中学 （国内高考班） 259 89"
  },
  {
    "serial": 24,
    "name": "深圳市第三高级中学 （国家留学基金委自费出国留学班）",
    "acQuota": 0,
    "dQuota": 0,
    "acdQuota": 188,
    "rawText": "24 深圳市第三高级中学 （国家留学基金委自费出国留学班） 188"
  },
  {
    "serial": 25,
    "name": "深圳启元中学",
    "acQuota": 274,
    "dQuota": 56,
    "acdQuota": 0,
    "rawText": "25 深圳启元中学 274 56"
  },
  {
    "serial": 26,
    "name": "深圳益新中学",
    "acQuota": 324,
    "dQuota": 62,
    "acdQuota": 0,
    "rawText": "26 深圳益新中学 324 62"
  },
  {
    "serial": 27,
    "name": "深圳大学附属中学中心校区 （深大附中中心校区）",
    "acQuota": 247,
    "dQuota": 74,
    "acdQuota": 0,
    "rawText": "27 深圳大学附属中学中心校区 （深大附中中心校区） 247 74"
  },
  {
    "serial": 28,
    "name": "深圳大学附属中学盐田校区 （深大附中盐田校区）",
    "acQuota": 140,
    "dQuota": 26,
    "acdQuota": 0,
    "rawText": "28 深圳大学附属中学盐田校区 （深大附中盐田校区） 140 26"
  },
  {
    "serial": 29,
    "name": "深圳大学附属实验中学",
    "acQuota": 252,
    "dQuota": 78,
    "acdQuota": 0,
    "rawText": "29 深圳大学附属实验中学 252 78"
  },
  {
    "serial": 30,
    "name": "深圳市第二实验学校",
    "acQuota": 190,
    "dQuota": 51,
    "acdQuota": 0,
    "rawText": "30 深圳市第二实验学校 190 51"
  },
  {
    "serial": 31,
    "name": "深圳市第二实验学校明远高中",
    "acQuota": 256,
    "dQuota": 75,
    "acdQuota": 0,
    "rawText": "31 深圳市第二实验学校明远高中 256 75"
  },
  {
    "serial": 32,
    "name": "深圳市第二高级中学",
    "acQuota": 421,
    "dQuota": 115,
    "acdQuota": 0,
    "rawText": "32 深圳市第二高级中学 421 115"
  },
  {
    "serial": 33,
    "name": "深圳市第二高级中学宝安高中部",
    "acQuota": 373,
    "dQuota": 67,
    "acdQuota": 0,
    "rawText": "33 深圳市第二高级中学宝安高中部 373 67"
  },
  {
    "serial": 34,
    "name": "深圳市第二高级中学深汕实验学校",
    "acQuota": 313,
    "dQuota": 137,
    "acdQuota": 0,
    "rawText": "34 深圳市第二高级中学深汕实验学校 313 137"
  },
  {
    "serial": 35,
    "name": "深圳第二外国语学校",
    "acQuota": 348,
    "dQuota": 134,
    "acdQuota": 0,
    "rawText": "35 深圳第二外国语学校 348 134"
  },
  {
    "serial": 36,
    "name": "深圳科学高中",
    "acQuota": 459,
    "dQuota": 130,
    "acdQuota": 0,
    "rawText": "36 深圳科学高中 459 130"
  },
  {
    "serial": 37,
    "name": "深圳科学高中龙岗分校",
    "acQuota": 228,
    "dQuota": 75,
    "acdQuota": 0,
    "rawText": "37 深圳科学高中龙岗分校 228 75"
  },
  {
    "serial": 38,
    "name": "深圳市第七高级中学",
    "acQuota": 386,
    "dQuota": 149,
    "acdQuota": 0,
    "rawText": "38 深圳市第七高级中学 386 149"
  },
  {
    "serial": 39,
    "name": "南方科技大学附属中学",
    "acQuota": 341,
    "dQuota": 99,
    "acdQuota": 0,
    "rawText": "39 南方科技大学附属中学 341 99"
  },
  {
    "serial": 40,
    "name": "广东实验中学深圳学校",
    "acQuota": 294,
    "dQuota": 91,
    "acdQuota": 0,
    "rawText": "40 广东实验中学深圳学校 294 91"
  },
  {
    "serial": 41,
    "name": "深圳技术大学附属中学",
    "acQuota": 240,
    "dQuota": 91,
    "acdQuota": 0,
    "rawText": "41 深圳技术大学附属中学 240 91"
  },
  {
    "serial": 42,
    "name": "东北师范大学附属中学深圳学校",
    "acQuota": 240,
    "dQuota": 91,
    "acdQuota": 0,
    "rawText": "42 东北师范大学附属中学深圳学校 240 91"
  },
  {
    "serial": 43,
    "name": "深圳北理莫斯科大学附属实验中学",
    "acQuota": 261,
    "dQuota": 69,
    "acdQuota": 0,
    "rawText": "43 深圳北理莫斯科大学附属实验中学 261 69"
  },
  {
    "serial": 44,
    "name": "深圳理工大学附属中学",
    "acQuota": 186,
    "dQuota": 35,
    "acdQuota": 0,
    "rawText": "44 深圳理工大学附属中学 186 35"
  },
  {
    "serial": 45,
    "name": "深圳市曙光中学（综合高中）",
    "acQuota": 326,
    "dQuota": 60,
    "acdQuota": 0,
    "rawText": "45 深圳市曙光中学（综合高中） 326 60"
  },
  {
    "serial": 46,
    "name": "深圳创新高级中学 （综合高中）",
    "acQuota": 294,
    "dQuota": 56,
    "acdQuota": 0,
    "rawText": "46 深圳创新高级中学 （综合高中） 294 56"
  },
  {
    "serial": 47,
    "name": "红岭中学",
    "acQuota": 529,
    "dQuota": 140,
    "acdQuota": 0,
    "rawText": "47 红岭中学 529 140"
  },
  {
    "serial": 48,
    "name": "福田中学",
    "acQuota": 435,
    "dQuota": 115,
    "acdQuota": 0,
    "rawText": "48 福田中学 435 115"
  },
  {
    "serial": 49,
    "name": "北京大学附属中学深圳学校",
    "acQuota": 207,
    "dQuota": 61,
    "acdQuota": 0,
    "rawText": "49 北京大学附属中学深圳学校 207 61"
  },
  {
    "serial": 50,
    "name": "西交利物浦大学基础教育集团外国语高级中学",
    "acQuota": 292,
    "dQuota": 83,
    "acdQuota": 0,
    "rawText": "50 西交利物浦大学基础教育集团外国语高级中学 292 83"
  },
  {
    "serial": 51,
    "name": "香港中文大学（深圳）附属明德高级中学",
    "acQuota": 266,
    "dQuota": 64,
    "acdQuota": 0,
    "rawText": "51 香港中文大学（深圳）附属明德高级中学 266 64"
  },
  {
    "serial": 52,
    "name": "翠园中学（爱国路校区）",
    "acQuota": 186,
    "dQuota": 34,
    "acdQuota": 0,
    "rawText": "52 翠园中学（爱国路校区） 186 34"
  },
  {
    "serial": 53,
    "name": "翠园中学（东门北路校区）",
    "acQuota": 267,
    "dQuota": 54,
    "acdQuota": 0,
    "rawText": "53 翠园中学（东门北路校区） 267 54"
  },
  {
    "serial": 54,
    "name": "罗湖高级中学",
    "acQuota": 196,
    "dQuota": 71,
    "acdQuota": 0,
    "rawText": "54 罗湖高级中学 196 71"
  },
  {
    "serial": 55,
    "name": "罗湖外语学校",
    "acQuota": 309,
    "dQuota": 76,
    "acdQuota": 0,
    "rawText": "55 罗湖外语学校 309 76"
  },
  {
    "serial": 56,
    "name": "深圳市美术学校",
    "acQuota": 156,
    "dQuota": 64,
    "acdQuota": 0,
    "rawText": "56 深圳市美术学校 156 64"
  },
  {
    "serial": 57,
    "name": "盐田高级中学",
    "acQuota": 407,
    "dQuota": 129,
    "acdQuota": 0,
    "rawText": "57 盐田高级中学 407 129"
  },
  {
    "serial": 58,
    "name": "南头中学",
    "acQuota": 360,
    "dQuota": 111,
    "acdQuota": 0,
    "rawText": "58 南头中学 360 111"
  },
  {
    "serial": 59,
    "name": "育才中学",
    "acQuota": 472,
    "dQuota": 79,
    "acdQuota": 0,
    "rawText": "59 育才中学 472 79"
  },
  {
    "serial": 60,
    "name": "育才一中",
    "acQuota": 267,
    "dQuota": 54,
    "acdQuota": 0,
    "rawText": "60 育才一中 267 54"
  },
  {
    "serial": 61,
    "name": "华侨城高级中学",
    "acQuota": 341,
    "dQuota": 87,
    "acdQuota": 0,
    "rawText": "61 华侨城高级中学 341 87"
  },
  {
    "serial": 62,
    "name": "北京师范大学南山附属学校",
    "acQuota": 181,
    "dQuota": 40,
    "acdQuota": 0,
    "rawText": "62 北京师范大学南山附属学校 181 40"
  },
  {
    "serial": 63,
    "name": "南山外国语学校（集团）高级中学",
    "acQuota": 259,
    "dQuota": 62,
    "acdQuota": 0,
    "rawText": "63 南山外国语学校（集团）高级中学 259 62"
  },
  {
    "serial": 64,
    "name": "宝安中学（集团）高中部",
    "acQuota": 436,
    "dQuota": 99,
    "acdQuota": 0,
    "rawText": "64 宝安中学（集团）高中部 436 99"
  },
  {
    "serial": 65,
    "name": "新安中学（集团）高中部",
    "acQuota": 326,
    "dQuota": 102,
    "acdQuota": 0,
    "rawText": "65 新安中学（集团）高中部 326 102"
  },
  {
    "serial": 66,
    "name": "宝安第一外国语学校",
    "acQuota": 307,
    "dQuota": 95,
    "acdQuota": 0,
    "rawText": "66 宝安第一外国语学校 307 95"
  },
  {
    "serial": 67,
    "name": "西乡中学",
    "acQuota": 396,
    "dQuota": 139,
    "acdQuota": 0,
    "rawText": "67 西乡中学 396 139"
  },
  {
    "serial": 68,
    "name": "沙井中学",
    "acQuota": 226,
    "dQuota": 99,
    "acdQuota": 0,
    "rawText": "68 沙井中学 226 99"
  },
  {
    "serial": 69,
    "name": "松岗中学",
    "acQuota": 119,
    "dQuota": 42,
    "acdQuota": 0,
    "rawText": "69 松岗中学 119 42"
  },
  {
    "serial": 70,
    "name": "石岩外国语学校",
    "acQuota": 176,
    "dQuota": 72,
    "acdQuota": 0,
    "rawText": "70 石岩外国语学校 176 72"
  },
  {
    "serial": 71,
    "name": "深圳市福海中学",
    "acQuota": 272,
    "dQuota": 82,
    "acdQuota": 0,
    "rawText": "71 深圳市福海中学 272 82"
  },
  {
    "serial": 72,
    "name": "深圳市龙津中学",
    "acQuota": 417,
    "dQuota": 161,
    "acdQuota": 0,
    "rawText": "72 深圳市龙津中学 417 161"
  },
  {
    "serial": 73,
    "name": "深圳市燕川中学",
    "acQuota": 414,
    "dQuota": 164,
    "acdQuota": 0,
    "rawText": "73 深圳市燕川中学 414 164"
  },
  {
    "serial": 74,
    "name": "龙城高级中学",
    "acQuota": 413,
    "dQuota": 123,
    "acdQuota": 0,
    "rawText": "74 龙城高级中学 413 123"
  },
  {
    "serial": 75,
    "name": "平冈中学",
    "acQuota": 286,
    "dQuota": 89,
    "acdQuota": 0,
    "rawText": "75 平冈中学 286 89"
  },
  {
    "serial": 76,
    "name": "深圳市龙岗区第二高级中学",
    "acQuota": 373,
    "dQuota": 163,
    "acdQuota": 0,
    "rawText": "76 深圳市龙岗区第二高级中学 373 163"
  },
  {
    "serial": 77,
    "name": "布吉中学",
    "acQuota": 159,
    "dQuota": 71,
    "acdQuota": 0,
    "rawText": "77 布吉中学 159 71"
  },
  {
    "serial": 78,
    "name": "横岗高级中学",
    "acQuota": 299,
    "dQuota": 130,
    "acdQuota": 0,
    "rawText": "78 横岗高级中学 299 130"
  },
  {
    "serial": 79,
    "name": "平湖外国语学校",
    "acQuota": 122,
    "dQuota": 54,
    "acdQuota": 0,
    "rawText": "79 平湖外国语学校 122 54"
  },
  {
    "serial": 80,
    "name": "华中师范大学龙岗附属中学",
    "acQuota": 386,
    "dQuota": 149,
    "acdQuota": 0,
    "rawText": "80 华中师范大学龙岗附属中学 386 149"
  },
  {
    "serial": 81,
    "name": "龙岗区实验高级中学",
    "acQuota": 162,
    "dQuota": 58,
    "acdQuota": 0,
    "rawText": "81 龙岗区实验高级中学 162 58"
  },
  {
    "serial": 82,
    "name": "龙华中学",
    "acQuota": 146,
    "dQuota": 65,
    "acdQuota": 0,
    "rawText": "82 龙华中学 146 65"
  },
  {
    "serial": 83,
    "name": "观澜中学",
    "acQuota": 402,
    "dQuota": 148,
    "acdQuota": 0,
    "rawText": "83 观澜中学 402 148"
  },
  {
    "serial": 84,
    "name": "龙华高级中学",
    "acQuota": 249,
    "dQuota": 72,
    "acdQuota": 0,
    "rawText": "84 龙华高级中学 249 72"
  },
  {
    "serial": 85,
    "name": "深圳市艺术高中",
    "acQuota": 156,
    "dQuota": 65,
    "acdQuota": 0,
    "rawText": "85 深圳市艺术高中 156 65"
  },
  {
    "serial": 86,
    "name": "深圳市格致中学",
    "acQuota": 237,
    "dQuota": 93,
    "acdQuota": 0,
    "rawText": "86 深圳市格致中学 237 93"
  },
  {
    "serial": 87,
    "name": "深圳市红山中学",
    "acQuota": 237,
    "dQuota": 93,
    "acdQuota": 0,
    "rawText": "87 深圳市红山中学 237 93"
  },
  {
    "serial": 88,
    "name": "深圳市龙华外国语高级中学",
    "acQuota": 237,
    "dQuota": 93,
    "acdQuota": 0,
    "rawText": "88 深圳市龙华外国语高级中学 237 93"
  },
  {
    "serial": 89,
    "name": "深圳市致理中学",
    "acQuota": 622,
    "dQuota": 203,
    "acdQuota": 0,
    "rawText": "89 深圳市致理中学 622 203"
  },
  {
    "serial": 90,
    "name": "深圳市龙华科技实验高级中学",
    "acQuota": 687,
    "dQuota": 166,
    "acdQuota": 0,
    "rawText": "90 深圳市龙华科技实验高级中学 687 166"
  },
  {
    "serial": 91,
    "name": "坪山高级中学",
    "acQuota": 294,
    "dQuota": 106,
    "acdQuota": 0,
    "rawText": "91 坪山高级中学 294 106"
  },
  {
    "serial": 92,
    "name": "深圳市聚龙科学中学",
    "acQuota": 394,
    "dQuota": 157,
    "acdQuota": 0,
    "rawText": "92 深圳市聚龙科学中学 394 157"
  },
  {
    "serial": 93,
    "name": "光明区高级中学",
    "acQuota": 555,
    "dQuota": 216,
    "acdQuota": 0,
    "rawText": "93 光明区高级中学 555 216"
  },
  {
    "serial": 94,
    "name": "光明中学",
    "acQuota": 224,
    "dQuota": 97,
    "acdQuota": 0,
    "rawText": "94 光明中学 224 97"
  },
  {
    "serial": 95,
    "name": "中国科学院深圳理工大学附属实验高级中学 （中科附高）",
    "acQuota": 280,
    "dQuota": 105,
    "acdQuota": 0,
    "rawText": "95 中国科学院深圳理工大学附属实验高级中学 （中科附高） 280 105"
  },
  {
    "serial": 96,
    "name": "人大附中深圳学校",
    "acQuota": 395,
    "dQuota": 105,
    "acdQuota": 0,
    "rawText": "96 人大附中深圳学校 395 105"
  },
  {
    "serial": 97,
    "name": "红岭教育集团大鹏华侨中学",
    "acQuota": 252,
    "dQuota": 78,
    "acdQuota": 0,
    "rawText": "97 红岭教育集团大鹏华侨中学 252 78"
  }
] as const;

export const privateHighSchoolPlans2026 = [
  {
    "serial": 1,
    "name": "深圳市罗湖区华美外国语学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "1 深圳市罗湖区华美外国语学校 民办 380 全住宿 ACD类考生 盐田区 面向全市招收 中考英语总成绩须"
  },
  {
    "serial": 2,
    "name": "深圳市万科梅沙书院",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "2 深圳市万科梅沙书院 民办 175 全住宿 ACD类考生 达B+级及以上 面向全市招收"
  },
  {
    "serial": 3,
    "name": "深圳市盐田区梅沙双语学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "3 深圳市盐田区梅沙双语学校 民办 240 全住宿 ACD类考生 南山区 民办（中 面向全市招收"
  },
  {
    "serial": 4,
    "name": "深圳（南山）中加学校",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "4 深圳（南山）中加学校 省一级 395 全住宿 外合作） ACD类考生 面向全市招收"
  },
  {
    "serial": 5,
    "name": "深圳市南山中英文学校",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "5 深圳市南山中英文学校 省一级 民办 300 全住宿 ACD类考生 宝安区 面向全市招收"
  },
  {
    "serial": 6,
    "name": "深圳东方英文书院",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "6 深圳东方英文书院 省一级 民办 900 全住宿 ACD类考生 提供450个床 面向全市招收"
  },
  {
    "serial": 7,
    "name": "深圳市崛起实验中学",
    "level": "市一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "7 深圳市崛起实验中学 市一级 民办 540 位 ACD类考生 面向全市招收"
  },
  {
    "serial": 8,
    "name": "深圳市桃源居中澳实验学校",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "8 深圳市桃源居中澳实验学校 省一级 民办 1300 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 9,
    "name": "深圳市华胜实验学校",
    "level": "市一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "9 深圳市华胜实验学校 市一级 民办 600 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 10,
    "name": "深圳市富源学校",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "10 深圳市富源学校 省一级 民办 1060 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 11,
    "name": "深圳市华侨（康桥）书院",
    "level": "市一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "11 深圳市华侨（康桥）书院 市一级 民办 500 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 12,
    "name": "深圳市明德外语实验学校",
    "level": "市一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "12 深圳市明德外语实验学校 市一级 民办 450 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 13,
    "name": "深圳市宝安区中英公学",
    "level": "市一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "13 深圳市宝安区中英公学 市一级 民办 160 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 14,
    "name": "深圳市松岗中英文实验学校",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "14 深圳市松岗中英文实验学校 省一级 民办 350 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 15,
    "name": "深圳市宝安区翻身实验学校（西校区）",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "15 深圳市宝安区翻身实验学校（西校区） 省一级 民办 900 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 16,
    "name": "深圳市华一实验学校",
    "level": "市一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "16 深圳市华一实验学校 市一级 民办 700 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 17,
    "name": "深圳市福桥高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "17 深圳市福桥高级中学 民办 300 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 18,
    "name": "深圳市滨海高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "18 深圳市滨海高级中学 民办 640 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 19,
    "name": "深圳市弘毅高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": ""
  },
  {
    "serial": 20,
    "name": "深圳市龙岗区东升学校",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "20 深圳市龙岗区东升学校 省一级 民办 1200 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 21,
    "name": "深圳市建文外国语学校",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "21 深圳市建文外国语学校 省一级 民办 2300 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 22,
    "name": "深圳市龙岗区科城实验学校",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "22 深圳市龙岗区科城实验学校 省一级 民办 560 走读 ACD类考生 面向全市招收"
  },
  {
    "serial": 23,
    "name": "深圳市承翰学校",
    "level": "市一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "23 深圳市承翰学校 市一级 民办 790 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 24,
    "name": "深圳市坤翔高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "24 深圳市坤翔高级中学 民办 1500 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 25,
    "name": "深圳市龙岗区珊蒂泉外国语学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "25 深圳市龙岗区珊蒂泉外国语学校 民办 1200 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 26,
    "name": "深圳市枫叶学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "26 深圳市枫叶学校 民办 180 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 27,
    "name": "深圳市龙岗区德琳学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "27 深圳市龙岗区德琳学校 民办 750 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 28,
    "name": "深圳市鹏达高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "28 深圳市鹏达高级中学 民办 700 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 29,
    "name": "深圳菁华中英文实验中学",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "29 深圳菁华中英文实验中学 省一级 民办 1060 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 30,
    "name": "深圳市晟才高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "30 深圳市晟才高级中学 民办 440 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 31,
    "name": "深圳市中荟高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "31 深圳市中荟高级中学 民办 1200 全住宿 ACD类考生 龙华区 面向全市招收"
  },
  {
    "serial": 32,
    "name": "深圳市龙华中英文实验学校",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "32 深圳市龙华中英文实验学校 省一级 民办 500 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 33,
    "name": "深圳市美中学校",
    "level": "市一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "33 深圳市美中学校 市一级 民办 960 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 34,
    "name": "深圳市展华实验学校",
    "level": "省一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "34 深圳市展华实验学校 省一级 民办 400 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 35,
    "name": "深圳市格睿特高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "35 深圳市格睿特高级中学 民办 700 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 36,
    "name": "深圳市龙华区博恒实验学校",
    "level": "市一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "36 深圳市龙华区博恒实验学校 市一级 民办 560 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 37,
    "name": "深圳市汉开数理高中",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "37 深圳市汉开数理高中 民办 800 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 38,
    "name": "深圳市育华高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": ""
  },
  {
    "serial": 39,
    "name": "深圳市龙翔学校",
    "level": "市一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "39 深圳市龙翔学校 市一级 民办 1095 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 40,
    "name": "深圳市中新中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "40 深圳市中新中学 民办 450 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 41,
    "name": "深圳市立人高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "41 深圳市立人高级中学 民办 700 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 42,
    "name": "深圳市华朗学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "42 深圳市华朗学校 民办 500 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 43,
    "name": "深圳市知源高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "43 深圳市知源高级中学 民办 500 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 44,
    "name": "深圳市华文高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "44 深圳市华文高级中学 民办 350 全住宿 ACD类考生 光明区 面向全市招收"
  },
  {
    "serial": 45,
    "name": "深圳市光明书院",
    "level": "市一级",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "45 深圳市光明书院 市一级 民办 1400 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 46,
    "name": "深圳杰仁高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "46 深圳杰仁高级中学 民办 450 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 47,
    "name": "深圳市耀华外国语学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "47 深圳市耀华外国语学校 民办 300 全住宿 ACD类考生 面向全市招收"
  },
  {
    "serial": 48,
    "name": "深圳市光明区贝赛思外国语学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "48 深圳市光明区贝赛思外国语学校 民办 180 全住宿 ACD类考生 大鹏新区 面向全市招收"
  },
  {
    "serial": 49,
    "name": "深圳市正德高级中学",
    "level": "",
    "nature": "民办",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "49 深圳市正德高级中学 民办 400 全住宿 ACD类考生"
  }
] as const;

export const vocationalPlans2026 = [
  {
    "serial": 1,
    "name": "820 走读 面向全市招收ACD类考生 （职高校本部） 国家中职教育",
    "level": "",
    "nature": "",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "1 820 走读 面向全市招收ACD类考生 （职高校本部） 国家中职教育 公办 深圳市第一职业技术学校 改革发展示范校"
  },
  {
    "serial": 2,
    "name": "160 全住宿 面向全市招收ACD类考生 （职高坪山校区） 国家中职教育",
    "level": "",
    "nature": "",
    "totalPlan": 0,
    "accommodation": "",
    "rawText": "2 160 全住宿 面向全市招收ACD类考生 （职高坪山校区） 国家中职教育"
  },
  {
    "serial": 3,
    "name": "深圳市第二职业技术学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 1295,
    "accommodation": "全住宿",
    "rawText": "3 深圳市第二职业技术学校 公办 1295 全住宿 面向全市招收ACD类考生 含新疆班180人 改革发展示范校"
  },
  {
    "serial": 4,
    "name": "深圳市新鹏职业高级中学",
    "level": "市一级",
    "nature": "公办",
    "totalPlan": 225,
    "accommodation": "全住宿",
    "rawText": "4 深圳市新鹏职业高级中学 市一级 公办 225 全住宿 面向全市招收ACD类考生"
  },
  {
    "serial": 5,
    "name": "深圳市开放职业技术学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 1100,
    "accommodation": "提供690个床位",
    "rawText": "5 深圳市开放职业技术学校 公办 1100 提供690个床位 面向全市招收ACD类考生"
  },
  {
    "serial": 6,
    "name": "深圳元平特殊教育学校",
    "level": "市一级",
    "nature": "公办",
    "totalPlan": 195,
    "accommodation": "全住宿",
    "rawText": "6 深圳元平特殊教育学校 市一级 公办 195 全住宿 特殊教育学校，招收特殊类学生"
  },
  {
    "serial": 7,
    "name": "深圳市第二特殊教育学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 60,
    "accommodation": "全住宿",
    "rawText": "7 深圳市第二特殊教育学校 公办 60 全住宿 特殊教育学校，招收特殊类学生"
  },
  {
    "serial": 8,
    "name": "深圳市第三职业技术学校",
    "level": "省级重点",
    "nature": "公办",
    "totalPlan": 1000,
    "accommodation": "全住宿",
    "rawText": "8 深圳市第三职业技术学校 省级重点 公办 1000 全住宿 面向全市招收ACD类考生"
  },
  {
    "serial": 9,
    "name": "深圳艺术学校",
    "level": "省级重点",
    "nature": "公办",
    "totalPlan": 80,
    "accommodation": "全住宿",
    "rawText": "9 深圳艺术学校 省级重点 公办 80 全住宿 面向全市招收ACD类考生"
  },
  {
    "serial": 10,
    "name": "深圳市体育运动学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 250,
    "accommodation": "全住宿",
    "rawText": "10 深圳市体育运动学校 公办 250 全住宿 面向全市招收ACD类考生 深圳市奋达职业技术学校"
  },
  {
    "serial": 11,
    "name": "民办 2200 全住宿 面向全市招收ACD类考生 （总校区）",
    "level": "省级重点",
    "nature": "民办",
    "totalPlan": 2200,
    "accommodation": "全住宿",
    "rawText": "11 民办 2200 全住宿 面向全市招收ACD类考生 （总校区） 省级重点 深圳市奋达职业技术学校"
  },
  {
    "serial": 12,
    "name": "民办 800 全住宿 面向全市招收ACD类考生 （坪山教学点）",
    "level": "",
    "nature": "民办",
    "totalPlan": 800,
    "accommodation": "全住宿",
    "rawText": "12 民办 800 全住宿 面向全市招收ACD类考生 （坪山教学点）"
  },
  {
    "serial": 13,
    "name": "深圳市中嘉职业技术学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 1800,
    "accommodation": "全住宿",
    "rawText": "13 深圳市中嘉职业技术学校 民办 1800 全住宿 面向全市招收ACD类考生"
  },
  {
    "serial": 14,
    "name": "深圳技师学院",
    "level": "国家级重点",
    "nature": "公办",
    "totalPlan": 1670,
    "accommodation": "全住宿",
    "rawText": "14 深圳技师学院 国家级重点 公办 1670 全住宿 面向全市招收ACD类考生"
  },
  {
    "serial": 15,
    "name": "深圳鹏城技师学院",
    "level": "国家级重点",
    "nature": "公办",
    "totalPlan": 1470,
    "accommodation": "提供840个床位",
    "rawText": "15 深圳鹏城技师学院 国家级重点 公办 1470 提供840个床位 面向全市招收ACD类考生"
  },
  {
    "serial": 16,
    "name": "深圳市携创高级技工学校",
    "level": "国家级重点",
    "nature": "民办",
    "totalPlan": 3000,
    "accommodation": "全住宿",
    "rawText": "16 深圳市携创高级技工学校 国家级重点 民办 3000 全住宿 面向全市招收ACD类考生"
  },
  {
    "serial": 17,
    "name": "深圳市深德高级技工学校",
    "level": "国家级重点",
    "nature": "民办",
    "totalPlan": 2000,
    "accommodation": "全住宿",
    "rawText": "17 深圳市深德高级技工学校 国家级重点 民办 2000 全住宿 面向全市招收ACD类考生 地址：深圳市坪山区"
  },
  {
    "serial": 18,
    "name": "深圳市宝山技工学校",
    "level": "省级重点",
    "nature": "民办",
    "totalPlan": 1500,
    "accommodation": "全住宿",
    "rawText": "18 深圳市宝山技工学校 省级重点 民办 1500 全住宿 面向全市招收ACD类考生 坪山街道和强路7号 深圳市宝山技工学校 地址：深圳市宝安区"
  },
  {
    "serial": 19,
    "name": "民办 850 全住宿 面向全市招收ACD类考生 中科校区 新桥街道寮盛路19号",
    "level": "",
    "nature": "民办",
    "totalPlan": 850,
    "accommodation": "全住宿",
    "rawText": "19 民办 850 全住宿 面向全市招收ACD类考生 中科校区 新桥街道寮盛路19号"
  },
  {
    "serial": 20,
    "name": "深圳市科迪技工学校",
    "level": "省级重点",
    "nature": "民办",
    "totalPlan": 610,
    "accommodation": "全住宿",
    "rawText": "20 深圳市科迪技工学校 省级重点 民办 610 全住宿 面向全市招收ACD类考生"
  },
  {
    "serial": 21,
    "name": "深圳市华夏技工学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 1100,
    "accommodation": "全住宿",
    "rawText": "21 深圳市华夏技工学校 民办 1100 全住宿 面向全市招收ACD类考生"
  },
  {
    "serial": 22,
    "name": "深圳市宝民技工学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 320,
    "accommodation": "全住宿",
    "rawText": "22 深圳市宝民技工学校 民办 320 全住宿 面向全市招收ACD类考生"
  },
  {
    "serial": 23,
    "name": "深圳市智理技工学校",
    "level": "省级重点",
    "nature": "民办",
    "totalPlan": 1000,
    "accommodation": "全住宿",
    "rawText": "23 深圳市智理技工学校 省级重点 民办 1000 全住宿 面向全市招收ACD类考生"
  },
  {
    "serial": 24,
    "name": "深圳市深科技工学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 1700,
    "accommodation": "全住宿",
    "rawText": "24 深圳市深科技工学校 民办 1700 全住宿 面向全市招收ACD类考生"
  },
  {
    "serial": 25,
    "name": "深圳市中特技工学校",
    "level": "",
    "nature": "民办",
    "totalPlan": 450,
    "accommodation": "提供380个床位",
    "rawText": "25 深圳市中特技工学校 民办 450 提供380个床位 面向全市招收ACD类考生 福田区 深圳市福田区华强职业技 国家中职教育"
  },
  {
    "serial": 26,
    "name": "公办 1090 走读 面向全市招收ACD类考生 术学校 改革发展示范校 罗湖区",
    "level": "",
    "nature": "公办",
    "totalPlan": 1090,
    "accommodation": "走读",
    "rawText": "26 公办 1090 走读 面向全市招收ACD类考生 术学校 改革发展示范校 罗湖区"
  },
  {
    "serial": 27,
    "name": "深圳市行知职业技术学校",
    "level": "国家级重点",
    "nature": "公办",
    "totalPlan": 510,
    "accommodation": "提供130个床位",
    "rawText": "27 深圳市行知职业技术学校 国家级重点 公办 510 提供130个床位 面向全市招收ACD类考生 盐田区"
  },
  {
    "serial": 28,
    "name": "深圳市盐港中学",
    "level": "市一级",
    "nature": "公办",
    "totalPlan": 750,
    "accommodation": "提供80个床位",
    "rawText": "28 深圳市盐港中学 市一级 公办 750 提供80个床位 面向全市招收ACD类考生 序号 学校（校区）名称 学校等级 办学性质 招生计划 住宿情况 招生范围 备注 南山区"
  },
  {
    "serial": 29,
    "name": "深圳市博伦职业技术学校",
    "level": "省级重点",
    "nature": "公办",
    "totalPlan": 1228,
    "accommodation": "提供500个床位",
    "rawText": "29 深圳市博伦职业技术学校 省级重点 公办 1228 提供500个床位 面向全市招收ACD类考生 宝安区 国家中职教育"
  },
  {
    "serial": 30,
    "name": "深圳市宝安职业技术学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 1380,
    "accommodation": "全住宿",
    "rawText": "30 深圳市宝安职业技术学校 公办 1380 全住宿 面向全市招收ACD类考生 改革发展示范校"
  },
  {
    "serial": 31,
    "name": "深圳市沙井职业高级中学",
    "level": "",
    "nature": "公办",
    "totalPlan": 570,
    "accommodation": "提供210个床位",
    "rawText": "31 深圳市沙井职业高级中学 公办 570 提供210个床位 面向全市招收ACD类考生 龙岗区 国家中职教育"
  },
  {
    "serial": 32,
    "name": "深圳市龙岗职业技术学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 880,
    "accommodation": "全住宿",
    "rawText": "32 深圳市龙岗职业技术学校 公办 880 全住宿 面向全市招收ACD类考生 改革发展示范校 深圳市龙岗区第二职业技"
  },
  {
    "serial": 33,
    "name": "省级重点",
    "level": "省级重点",
    "nature": "公办",
    "totalPlan": 970,
    "accommodation": "全住宿",
    "rawText": "33 省级重点 公办 970 全住宿 面向全市招收ACD类考生 术学校 龙华区"
  },
  {
    "serial": 34,
    "name": "深圳市龙华职业技术学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 660,
    "accommodation": "全住宿",
    "rawText": "34 深圳市龙华职业技术学校 公办 660 全住宿 面向全市招收ACD类考生 光明区 深圳市光明区中等职业技"
  },
  {
    "serial": 35,
    "name": "公办 120 全住宿 面向全市招收ACD类考生 借址办学 术学校",
    "level": "",
    "nature": "公办",
    "totalPlan": 120,
    "accommodation": "全住宿",
    "rawText": "35 公办 120 全住宿 面向全市招收ACD类考生 借址办学 术学校"
  }
] as const;
